# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PenguinCam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PenguinCam
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'PenguinCamTests' do
    inherit! :search_paths
    
    # Pods for testing
  end

  target 'PenguinCamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
